create table "copyfuse"."members" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "first_name" text,
    "surname" text,
    "email" text not null,
    "pending" boolean not null default true
);


alter table "copyfuse"."members" enable row level security;

CREATE UNIQUE INDEX pending_members_pkey ON copyfuse.members USING btree (id);

alter table "copyfuse"."members" add constraint "pending_members_pkey" PRIMARY KEY using index "pending_members_pkey";


