create table "copyfuse"."networks" (
    "id" bigint generated by default as identity not null,
    "code" text not null,
    "name" text not null,
    "description" text not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
);


alter table "copyfuse"."networks" enable row level security;

CREATE UNIQUE INDEX networks_pkey ON copyfuse.networks USING btree (id);

alter table "copyfuse"."networks" add constraint "networks_pkey" PRIMARY KEY using index "networks_pkey";

grant all on table copyfuse.networks to authenticated;
