create table "copyfuse"."activities" (
    "id" bigint generated by default as identity not null,
    "networks" bigint,
    "members" bigint,
    "activity_category" text not null,
    "activity_json" jsonb,
    "created_at" timestamp with time zone not null default now()
);


alter table "copyfuse"."activities" enable row level security;

CREATE UNIQUE INDEX activities_pkey ON copyfuse.activities USING btree (id);

alter table "copyfuse"."activities" add constraint "activities_pkey" PRIMARY KEY using index "activities_pkey";

alter table "copyfuse"."activities" add constraint "activities_members_fkey" FOREIGN KEY (members) REFERENCES copyfuse.members(id) ON DELETE SET NULL not valid;

alter table "copyfuse"."activities" validate constraint "activities_members_fkey";

alter table "copyfuse"."activities" add constraint "activities_networks_fkey" FOREIGN KEY (networks) REFERENCES copyfuse.networks(id) ON DELETE SET NULL not valid;

alter table "copyfuse"."activities" validate constraint "activities_networks_fkey";

grant all on table copyfuse.activities to authenticated;