create table "copyfuse"."member" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "first_name" text,
    "surname" text,
    "email" text not null,
    "pending" boolean not null default true
);


alter table "copyfuse"."member" enable row level security;

CREATE UNIQUE INDEX pending_member_pkey ON copyfuse.member USING btree (id);

alter table "copyfuse"."member" add constraint "pending_member_pkey" PRIMARY KEY using index "pending_member_pkey";


